name: Test package manager execution
on: 
  workflow_dispatch:
    inputs: 
      tag:
        description: 'Release tag to test, i.e latest, 1.0.0. Default latest'
        required: false
        default: latest

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        package-manager:
          [
            {
              name: "yarn",
              exec: "yarn dlx",
              preExec: "yarn set version berry"
            },
            { name: "pnpm", exec: "pnpm dlx", preExec: "" },
            { name: "npm", exec: "npm -y x", preExec: "" }
          ]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install package manager"
        run: npm install -g ${{ matrix.package-manager.name }}
      - name: "Package manager pre-exec"
        run: ${{ matrix.package-manager.preExec }}
      - name: Check if Plasmo command works
        run: ${{ matrix.package-manager.exec }} plasmo@${{ github.event.inputs.tag  }} version
      - name: "Package manager pre-exec Part Two"
        run: ${{ matrix.package-manager.preExec }}
      - name: Check if plasmo init works at all
        run: |
          YARN_ENABLE_IMMUTABLE_INSTALLS=false 
          echo "testdir" | ${{ matrix.package-manager.exec }} plasmo@${{ github.event.inputs.tag }}  init --verbose
      - name: Check if building is possible and if it built
        run: |
          pushd testdir
          ${{ matrix.package-manager.name }} run build
          pushd build
