name: Test examples
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@master
        with:
          submodules: "recursive"
      - name: "Install package manager"
        run: npm install -g pnpm
      - name: "Build local version of Plasmo"
        run: |
          pnpm i --no-frozen-lockfile
          pnpm run build:packages
          pnpm i
          pnpm run build:cli
          pnpm i
      - name: "Go to each example and try to build it"
        run: |
          pnpm run build:examples
          # pushd examples
          # for d in *
          # do
          #   test -d "$d" || continue
          #   pushd "$d"
          #   rm -rf .plasmo
          #   rm -rf build
          #   timeout 5 pnpm dev || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
          #   popd
          # done
          # popd
